import { StyleSheet } from "@react-pdf/renderer";
import { BNI_GREY, BNI_RED } from "@/lib/constants";

export const bookletStyles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 28,
    fontFamily: "Helvetica",
    fontSize: 8.5,
    color: "#111111",
  },
  guestPage: {
    paddingTop: 24,
    paddingBottom: 24,
    paddingHorizontal: 28,
    fontFamily: "Helvetica",
    fontSize: 8.5,
    color: "#111111",
  },
  coverPage: {
    paddingTop: 24,
    paddingBottom: 24,
    paddingHorizontal: 32,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#111111",
    backgroundColor: "#ffffff",
  },
  coverTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  coverChapterLogo: {
    width: 72,
    height: 72,
    objectFit: "contain",
  },
  coverVenueLogo: {
    width: 120,
    height: 48,
    objectFit: "contain",
  },
  coverLogoPlaceholder: {
    width: 72,
    height: 48,
    backgroundColor: "#f5f5f5",
    border: "1px solid #e8e8e8",
    borderRadius: 4,
  },
  coverHero: {
    alignItems: "center",
    marginBottom: 14,
    paddingBottom: 12,
    borderBottom: "1px solid #ececec",
  },
  coverEyebrow: {
    fontSize: 8,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: BNI_GREY,
    marginBottom: 8,
  },
  coverTitle: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 0.3,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  coverWebsiteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  coverWebsite: {
    fontSize: 9.5,
    color: BNI_GREY,
  },
  coverChapterQrBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    border: "1px solid #64b4f5",
    borderRadius: 6,
    backgroundColor: "#f3faff",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  coverChapterQr: {
    width: 30,
    height: 30,
    backgroundColor: "#ffffff",
    padding: 2,
    borderRadius: 3,
  },
  coverChapterQrTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#2d6fa8",
    lineHeight: 1.2,
  },
  coverVenueCard: {
    flexDirection: "row",
    gap: 16,
    border: "1px solid #e2e2e2",
    borderRadius: 6,
    padding: 12,
    marginBottom: 16,
    backgroundColor: "#fafafa",
  },
  coverVenuePhoto: {
    width: 130,
    height: 96,
    borderRadius: 4,
    objectFit: "cover",
  },
  coverVenuePhotoPlaceholder: {
    width: 130,
    height: 96,
    borderRadius: 4,
    backgroundColor: "#efefef",
    border: "1px dashed #d0d0d0",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  coverVenuePhotoPlaceholderText: {
    fontSize: 7,
    color: BNI_GREY,
  },
  coverVenueDetails: {
    flex: 1,
    justifyContent: "center",
    gap: 6,
  },
  coverVenueLabel: {
    fontSize: 8,
    fontWeight: "bold",
    color: BNI_RED,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  coverDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  coverDetailIcon: {
    width: 12,
    alignItems: "center",
  },
  coverDetailText: {
    fontSize: 9.5,
    color: "#222222",
    lineHeight: 1.35,
    flex: 1,
  },
  coverCoreValuesSection: {
    marginBottom: 12,
  },
  coverSectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: BNI_RED,
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  coreValuesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  coreValueCard: {
    width: "31%",
    border: "1px solid #e8e8e8",
    borderRadius: 4,
    padding: 7,
    backgroundColor: "#ffffff",
    minHeight: 62,
  },
  coreValueIconWrap: {
    width: 18,
    height: 18,
    marginBottom: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  coreValueCustomIcon: {
    width: 16,
    height: 16,
    objectFit: "contain",
  },
  coreValueTitle: {
    fontSize: 8,
    fontWeight: "bold",
    marginBottom: 3,
    lineHeight: 1.2,
  },
  coreValueDescription: {
    fontSize: 6.5,
    color: BNI_GREY,
    lineHeight: 1.3,
  },
  feedbackBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: BNI_RED,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 4,
  },
  feedbackQr: {
    width: 46,
    height: 46,
    backgroundColor: "#ffffff",
    padding: 4,
    borderRadius: 4,
  },
  feedbackCopy: {
    flex: 1,
  },
  feedbackTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  feedbackTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  feedbackSubtitle: {
    fontSize: 8.5,
    color: "#ffe8ea",
    lineHeight: 1.35,
  },
  coverSubtitle: {
    fontSize: 11,
    textAlign: "center",
    color: BNI_GREY,
    marginTop: 16,
    lineHeight: 1.5,
  },
  coverAccent: {
    fontSize: 12,
    textAlign: "center",
    color: BNI_RED,
    marginTop: 24,
    fontWeight: "bold",
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: BNI_RED,
    marginBottom: 10,
  },
  subHeading: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 4,
    marginTop: 8,
  },
  body: {
    fontSize: 9,
    color: BNI_GREY,
    lineHeight: 1.4,
  },
  roleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottom: "1px solid #ececec",
    paddingVertical: 4,
  },
  roleTitle: {
    fontWeight: "bold",
    width: "45%",
  },
  roleName: {
    width: "55%",
  },
  leadershipChart: {
    marginBottom: 8,
  },
  leaderTier: {
    border: "1px solid #e2e2e2",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 6,
    backgroundColor: "#fafafa",
    marginBottom: 4,
  },
  leaderConnector: {
    alignSelf: "center",
    width: 1,
    height: 6,
    backgroundColor: "#d0d0d0",
    marginBottom: 1,
  },
  leaderTierLabel: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: BNI_RED,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    textAlign: "center",
    marginBottom: 6,
  },
  leaderTierRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 4,
    marginBottom: 4,
  },
  leaderNode: {
    alignItems: "center",
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  leaderAvatar: {
    marginBottom: 3,
    objectFit: "cover",
  },
  leaderAvatarPlaceholder: {
    backgroundColor: "#ececec",
    border: "1px solid #d6d6d6",
    alignItems: "center",
    justifyContent: "center",
  },
  leaderInitials: {
    fontSize: 8,
    fontWeight: "bold",
    color: BNI_GREY,
  },
  leaderName: {
    fontSize: 7,
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 1.2,
    marginBottom: 2,
  },
  leaderRole: {
    fontSize: 6,
    color: BNI_GREY,
    textAlign: "center",
    lineHeight: 1.25,
  },
  charitySectionRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    marginTop: 8,
  },
  charityBadgeColumn: {
    flex: 3,
  },
  charityBankColumn: {
    flex: 2,
  },
  charityColumnFull: {
    flex: 1,
  },
  charityFootnote: {
    marginTop: 5,
    paddingHorizontal: 2,
  },
  charityFootnoteParagraph: {
    fontSize: 5.5,
    color: "#8a8a8a",
    lineHeight: 1.3,
    textAlign: "center",
  },
  charityFootnoteGap: {
    marginBottom: 4,
  },
  charityBadge: {
    position: "relative",
    border: "1px solid #64b4f5",
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#f7fbff",
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 12,
  },
  charityBadgeSideAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
  },
  charityBadgeAccent: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 4,
  },
  charityBadgeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
    paddingLeft: 4,
  },
  charityBadgeHeaderCopy: {
    flex: 1,
  },
  charityBadgeEyebrow: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#ffb71c",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  charityBadgeTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#2d6fa8",
    lineHeight: 1.2,
  },
  charityBadgeLogo: {
    width: 44,
    height: 44,
    objectFit: "contain",
  },
  charityBadgeParagraph: {
    fontSize: 8,
    color: "#3d4f5f",
    lineHeight: 1.4,
    marginBottom: 8,
    paddingLeft: 4,
  },
  charityQrPanel: {
    backgroundColor: "#ffffff",
    border: "1px solid #d9ecfb",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  charityQrRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 8,
  },
  charityQrCard: {
    width: "31%",
    alignItems: "center",
  },
  charityQrFrame: {
    backgroundColor: "#ffffff",
    border: "2px solid #ffb71c",
    borderRadius: 6,
    padding: 5,
    marginBottom: 5,
  },
  charityQrImage: {
    width: 50,
    height: 50,
  },
  charityQrLabel: {
    fontSize: 7,
    fontWeight: "bold",
    color: "#2d6fa8",
    textAlign: "center",
    lineHeight: 1.25,
  },
  charityBankBox: {
    backgroundColor: "#f2f2f2",
    border: "1px solid #d8d8d8",
    borderRadius: 8,
    padding: 10,
  },
  charityBankBoxTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: BNI_GREY,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  charityBankPanel: {
    flexDirection: "column",
  },
  charityBankBlock: {
    marginBottom: 10,
    paddingBottom: 10,
    borderBottom: "1px solid #d0d0d0",
  },
  charityBankBlockLast: {
    marginBottom: 0,
    paddingBottom: 0,
  },
  charityBankTitle: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 5,
  },
  charityBankText: {
    fontSize: 7.5,
    color: BNI_GREY,
    lineHeight: 1.55,
    marginBottom: 3,
  },
  qrRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    gap: 8,
  },
  qrItem: {
    alignItems: "center",
    width: "30%",
  },
  qrImage: {
    width: 64,
    height: 64,
  },
  qrLabel: {
    fontSize: 8,
    textAlign: "center",
    marginTop: 4,
  },
  weekPage: {
    flexDirection: "column",
  },
  slotsColumn: {
    flexDirection: "column",
    flexGrow: 1,
    height: 730,
    gap: 10,
  },
  slotBox: {
    border: "1px solid #d9d9d9",
    borderRadius: 4,
    padding: 12,
    flex: 1,
  },
  slotTitle: {
    fontSize: 10,
    fontWeight: "bold",
    color: BNI_RED,
    marginBottom: 8,
  },
  slotBody: {
    fontSize: 9,
    color: BNI_GREY,
    lineHeight: 1.45,
  },
  pageTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: BNI_RED,
    marginBottom: 10,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  pageSubtitle: {
    fontSize: 8,
    color: BNI_GREY,
    textAlign: "center",
    marginBottom: 12,
  },
  table: {
    borderLeft: "1px solid #cfcfcf",
    borderRight: "1px solid #cfcfcf",
    borderTop: "1px solid #cfcfcf",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#f3f3f3",
    borderBottom: "1px solid #cfcfcf",
  },
  tableHeaderCell: {
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderRight: "1px solid #dedede",
  },
  tableHeaderText: {
    fontSize: 7.5,
    fontWeight: "bold",
    color: BNI_RED,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tableBodyRow: {
    flexDirection: "row",
    borderBottom: "1px solid #e4e4e4",
    minHeight: 96,
    alignItems: "stretch",
  },
  guestBodyRow: {
    flexDirection: "row",
    borderBottom: "1px solid #e4e4e4",
    minHeight: 34,
    alignItems: "stretch",
  },
  guestTableCell: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRight: "1px solid #e4e4e4",
    justifyContent: "center",
  },
  guestNotesCell: {
    borderRight: "none",
    paddingVertical: 5,
    paddingHorizontal: 8,
    justifyContent: "center",
  },
  tableCell: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRight: "1px solid #e4e4e4",
    justifyContent: "flex-start",
  },
  photoColumn: {
    alignItems: "center",
    gap: 6,
  },
  headshot: {
    width: 46,
    height: 46,
    borderRadius: 2,
    objectFit: "cover",
  },
  headshotPlaceholder: {
    backgroundColor: "#efefef",
    border: "1px solid #dddddd",
  },
  linkedInBlock: {
    alignItems: "center",
    gap: 3,
  },
  linkedInQr: {
    width: 40,
    height: 40,
  },
  linkedInBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  linkedInLabel: {
    fontSize: 6.5,
    color: "#0A66C2",
    fontWeight: "bold",
  },
  linkedInMissing: {
    alignItems: "center",
    gap: 2,
    opacity: 0.45,
  },
  linkedInMissingText: {
    fontSize: 6,
    color: BNI_GREY,
  },
  memberName: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 3,
    lineHeight: 1.25,
  },
  memberSeat: {
    fontSize: 8.5,
    color: BNI_RED,
    fontWeight: "bold",
    marginBottom: 3,
    lineHeight: 1.25,
  },
  memberRoles: {
    fontSize: 7.5,
    color: BNI_GREY,
    lineHeight: 1.35,
  },
  companyName: {
    fontSize: 9,
    fontWeight: "bold",
    marginBottom: 5,
    lineHeight: 1.25,
  },
  contactList: {
    gap: 3,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  contactIcon: {
    width: 10,
    alignItems: "center",
  },
  contactText: {
    fontSize: 7.5,
    color: "#333333",
    lineHeight: 1.25,
    flex: 1,
  },
  contactLink: {
    textDecoration: "none",
    color: "#333333",
  },
  notesCell: {
    borderRight: "none",
    paddingVertical: 10,
  },
  notesLines: {
    gap: 7,
    marginTop: 2,
  },
  noteLine: {
    borderBottom: "1px solid #cccccc",
    height: 12,
  },
  guestWriteLine: {
    borderBottom: "1px solid #cccccc",
    height: 12,
    marginTop: 2,
  },
  guestNoteLines: {
    gap: 4,
  },
  guestNoteLine: {
    borderBottom: "1px solid #cccccc",
    height: 10,
  },
});
